[cosmic-ray]
module-path = "pycalphad"
timeout = 15
excluded-modules = []
test-command = "uv run python run_pytest_and_capture.py -x --template=html1/index.html --report=report.html -s tests"

[cosmic-ray.distributor]
name = "http"

[cosmic-ray.distributor.http]
worker-urls = [
    "http://localhost:9001",
    "http://localhost:9002"
]