[cosmic-ray]
module-path = "pycalphad"
timeout = 30.0
excluded-modules = []
test-command = "uv run python -m pytest tests --template=html1/index.html --report=report.html -s"

[cosmic-ray.distributor]
name = "http"

[cosmic-ray.distributor.http]
worker-urls = [
    "http://localhost:9001",
    "http://localhost:9002"
]